TeamZeroFrontEnd/TeamZeroFrontEnd/Controllers/BicycleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using TeamZeroFrontEnd.Models;
using TeamZeroFrontEnd.Services;

namespace TeamZeroFrontEnd.Controllers
{
	[Authorize(Roles = "Admin")]
	public class BicycleController : Controller
	{
		public async Task<IActionResult> IndexAsync()
		{
			List<BicycleViewModel> model = await APIRequestHandler.GetAsync("bicycle") as List<BicycleViewModel>;
			if(model != null)
				return View(model);
			return View("~/Views/Home/Index.cshtml");
		}

		//GET: /bicycle/create
		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind] BicycleViewModel bicycle)
		{
			if (ModelState.IsValid)
			{
				var jsonContent = APIRequestHandler.SerializeObject(bicycle);
				var result = await APIRequestHandler.PostAsync("bicycle", jsonContent);
				if (result)
					return RedirectToAction("Index");
			}
			return View(bicycle);
		}


		[HttpGet]
		public async Task<IActionResult> DeleteAsync(int id)
		{
			BicycleViewModel model = await APIRequestHandler.GetAsync("bicycle", id) as BicycleViewModel;
			if(model != null)
				return View(model);
			return NotFound();
		}

		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmedAsync(int id)
		{
			var result = await APIRequestHandler.DeleteAsync("bicycle", id);
			if (result)
				return RedirectToAction("Index");
			return View("~/Views/Shared/Erorr.cshtml");
		}

		[HttpGet]
		public async Task<IActionResult> EditAsync(int id)
		{
			BicycleViewModel model = await APIRequestHandler.GetAsync("bicycle", id) as BicycleViewModel;
			if(model != null)
				return View(model);
			return NotFound();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> EditAsync(int id, [Bind]BicycleViewModel bicycle)
		{
			var content = APIRequestHandler.SerializeObject(bicycle);
			var result = await APIRequestHandler.UpdateAsync("bicycle", id, content);
			if (result)
				return RedirectToAction("Index");
			return View("~/Views/Shared/Erorr.cshtml");
		}

		[HttpGet]
		public async Task<IActionResult> Details(int id)
		{
			var bike = await APIRequestHandler.GetAsync("bicycle", id);
			if (bike != null)
				return View(bike);
			return NotFound();
		}

	}
}

TeamZeroFrontEnd/TeamZeroFrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TeamZeroFrontEnd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand ml-auto" asp-area="" asp-controller="Home" asp-action="Index">TeamZeroFrontEnd</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @{
                            if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Bicycle" asp-action="Index">Bicycles</a>
                                </li>
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Careers">Careers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="~/Shop/1">Shop</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top border-dark footer text-muted">
        <div class="container">
            &copy; 2021 - TeamZeroFrontEnd - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>